version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - main
    steps:
      - checkout
      - run:
          name: Install Yarn 
          command: npm install -g yarn@1
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_imooc
      - run:
          name: Build
          command: yarn build