version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - npm
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_imooc
      - run:
          name: Build
          command: npm build